// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyonkeiqukcrgihvjgly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5b25rZWlxdWtjcmdpaHZqZ2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTM0MTIsImV4cCI6MjA1NTkyOTQxMn0.u9P6OW-5ztZ8N4EMRUeMciGBn6Ykh0qebnQ4bCiWsWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);